site_name: StableRLS Documentation
repo_url: https://github.com/rAnnuth/stablerls
docs_dir: docs

theme:
  name: cinder

nav:
  - Home: index.md
  - Getting Started:
    - "Installation": source/install.md
    - "Port Creation": source/port_creation.md
    - "Configuration": source/configuration.md
  - Components & Tools:
    - "Config Reader": source/configreader.md
    - "Create FMU": source/createFMU.md
    - "FMU Tools": source/fmutools.md
    - "Gym FMU": source/gymFMU.md
  - Examples:
    - "Overview": notebooks/overview.md
  - Reference:
    - "API Reference": source/API_Reference.md
    - "Contributing": source/contribute.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src"]
